source('w2-pollutantmean.R')
source('w2-complete.R')
source('w2-corr.R')
pollutantmean("w2-specdata", "sulfate", 1:10)
pollutantmean("w2-specdata", "nitrate", 70:72)
pollutantmean("w2-specdata", "sulfate", 34)
pollutantmean("w2-specdata", "nitrate")

cc <- complete("w2-specdata", c(6, 10, 20, 34, 100, 200, 310))
print(cc$nobs)

cc <- complete("w2-specdata", 54)
print(cc$nobs)

RNGversion("3.5.1")
set.seed(42)
cc <- complete("w2-specdata", 332:1)
use <- sample(332, 10)
print(cc[use, "nobs"])

cr <- corr("w2-specdata")
cr <- sort(cr)
RNGversion("3.5.1")
set.seed(868)
out <- round(cr[sample(length(cr), 5)], 4)
print(out)

cr <- corr("w2-specdata", 129)
cr <- sort(cr)
n <- length(cr)
RNGversion("3.5.1")
set.seed(197)
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)

cr <- corr("w2-specdata", 2000)
n <- length(cr)
cr <- corr("w2-specdata", 1000)
cr <- sort(cr)
print(c(n, round(cr, 4)))
